COLUMNS_TO_EXCLUDE = ['year_of_birth',
                      'disbursed_date',
                      'mobileno_flag',
                      'idcard_flag',
                      'enquirie_no',
                      'passport_flag',
                      'main_account_loan_no',
                      'main_account_active_loan_no',
                      'main_account_overdue_no',
                      'main_account_outstanding_loan',
                      'main_account_sanction_loan',
                      'main_account_disbursed_loan',
                      'main_account_monthly_payment',
                      'sub_account_loan_no',
                      'sub_account_active_loan_no',
                      'sub_account_overdue_no',
                      'sub_account_outstanding_loan',
                      'sub_account_sanction_loan',
                      'sub_account_monthly_payment',
                      'sub_account_disbursed_loan',
                      'disbursed_amount',
                      'main_account_inactive_loan_no',
                      'sub_account_inactive_loan_no',
                      'disburse_to_sactioned_ratio',
                      'outstanding_disburse_ratio',
                      'total_account_loan_no',
                      'total_inactive_loan_no',
                      'total_overdue_no',
                      'main_account_tenure',
                      'sub_account_tenure',
                      'credit_score',
                      'total_sanction_loan',
                      'asset_cost']

KEEP_ID = []

EXCLUDE_FROM_SCALING = ['Driving_flag',
                        'employment_type_0',
                        'employment_type_1',
                        'employment_type_2',
                        'age']
